#!/bin/bash
set -e

/usr/local/pg-db-migrate/write_config "$@" > /tmp/database.json
/usr/local/pg-db-migrate/wait_for_pg
cd /usr/local/pg-db-migrate
mkdir -p migrations
cp /migrations/* ./migrations/
./node_modules/.bin/db-migrate up --config /tmp/database.json
