#!/bin/bash
set -e

function check_connection() {
  set +e

  iteration=$1

  if (( $iteration > 5 ))
  then
    echo "Connection failed."
    exit 1;
  fi

  echo "Testing connection attempt $iteration"

  nc -z $DB_PORT_5432_TCP_ADDR $DB_PORT_5432_TCP_PORT

  if [[ "$?" -ne "0" ]]
  then
    sleep 1
    check_connection $((iteration + 1))
  else
    echo "Port is open!"
  fi

  set -e
}

check_connection 0

/usr/local/pg-db-migrate/write_config "$@" > /tmp/database.json
cd /usr/local/pg-db-migrate
mkdir -p migrations
cp /migrations/* ./migrations/
./node_modules/.bin/db-migrate up --config /tmp/database.json
