#!/usr/bin/env node

var pg = require("pg");
var config = require("/tmp/database");

var connString = [
  "postgres://",
  config.dev.user,
  ":",
  config.dev.password,
  "@",
  config.dev.host,
  "/",
  config.dev.database
].join("");

var attempts = 0;

function tryConnect() {
  console.log("Attempting connection");
  attempts++;

  pg.connect(connString, function (err) {
    if (err) {
      if (attempts > 20) {
        console.log("Failed to connect after 20 attempts.");
        process.exit(1);
      }
      console.log("Connection attempt failed")
      setTimeout(tryConnect, 1000);
    } else {
      console.log("Connected");
      process.exit(0);
    }
  });
}

tryConnect();
